### ISSUE TITLE
Suggest archiving this repo

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/MirrorKAN#12]
Trying to figure out what this repo was for, it looks like the CKAN team was trying to run a server, which served up some reshuffled metadata from GitHub? and also uploaded to archive.org? Was it an early ancestor of the bot/Infra?

It looks unused, and its code hasn't been changed since early 2015. Can we retire it?

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories

(Not to be confused with KSP-CKAN/NetKAN-bot#94, which is suggesting archiving newer code of which I do understand the purpose.)

**Comment by DasSkelett** [comment]
Looks worthy for archiving to me as well.
Going to archive it now, if needed we can unarchive it again.

**Comment by DasSkelett** [comment]
Archiving now :tada:
