### ISSUE TITLE
expose "indexed|ckan" image for wiki pages

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/MirrorKAN#5]
According to @leftler, the wiki pages can't reference the raw image binary from the github repository.

After cloning the CKAN repository, put the assets to somewhere where the web server can expose them.

**Comment by DasSkelett** [comment]
You can, if you reference the "raw" link, e.g. `https://raw.githubusercontent.com/KSP-CKAN/CKAN/6b2340cff825648b4a883e25a479ca201b95dab5/assets/ckan-indexed.svg`

![](https://raw.githubusercontent.com/KSP-CKAN/CKAN/6b2340cff825648b4a883e25a479ca201b95dab5/assets/ckan-indexed.svg)
